microsoft/pgtoolsservice

.vscode/launch.json
pgsmo/objects/functions/templates_functions/pg/11.0_plus/coll_stats.sql
pgsmo/objects/functions/templates_functions/pg/11.0_plus/create.sql
pgsmo/objects/functions/templates_functions/pg/11.0_plus/delete.sql
pgsmo/objects/functions/templates_functions/pg/11.0_plus/get_definition.sql
pgsmo/objects/functions/templates_functions/pg/11.0_plus/get_oid.sql
pgsmo/objects/functions/templates_functions/pg/11.0_plus/nodes.sql
pgsmo/objects/functions/templates_functions/pg/11.0_plus/properties.sql
pgsmo/objects/functions/templates_functions/pg/11.0_plus/update.sql
pgsmo/objects/functions/templates_functions/pg/9.5_plus/properties.sql
pgsmo/objects/functions/templates_functions/ppas/11.0_plus/coll_stats.sql
pgsmo/objects/functions/templates_functions/ppas/11.0_plus/delete.sql
pgsmo/objects/functions/templates_functions/ppas/11.0_plus/get_definition.sql
pgsmo/objects/functions/templates_functions/ppas/11.0_plus/get_oid.sql
pgsmo/objects/functions/templates_functions/ppas/11.0_plus/node.sql
pgsmo/objects/functions/templates_functions/ppas/11.0_plus/properties.sql
pgsmo/objects/table_objects/constraint_exclusion/11.0_plus/create.sql
pgsmo/objects/table_objects/constraint_exclusion/11.0_plus/get_constraint_include.sql
pgsmo/objects/table_objects/constraint_exclusion/11.0_plus/properties.sql
pgsmo/objects/table_objects/constraint_index/11.0_plus/create.sql
pgsmo/objects/table_objects/constraint_index/11.0_plus/get_constraint_include.sql
pgsmo/objects/table_objects/constraint_index/11.0_plus/properties.sql
pgsmo/objects/table_objects/index/11.0_plus/column_details.sql
pgsmo/objects/table_objects/index/11.0_plus/create.sql
pgsmo/objects/table_objects/index/11.0_plus/include_details.sql
pgsmo/utils/templating.py
pgsqltoolsservice/converters/bytes_to_any_converters.py
pgsqltoolsservice/pgtoolsservice_main.py
requirements.txt
tests/query/data_storage/test_service_buffer_file_stream_reader.py

- Include PG 11 script files to resolve expanding of functions in PG 11 https://github.com/microsoft/azuredatastudio-postgresql/issues/100
- Fix debugging issue

Include PG11 script files

---

pgsqltoolsservice/workspace/workspace.py
requirements.txt

- Unquoting the file uri before using it as a key in dict
- Lowering the version of ptvsd to original as the have some issues related to _pydevd_bundle with new one

Fix for No file corresponding to the given URI

---

pgsqltoolsservice/edit_data/update_management/row_edit.py
requirements.txt
tests/edit_data/data_management/test_row_create.py
tests/edit_data/data_management/test_row_delete.py
tests/edit_data/test_data_editor_session.py

We had issues connection PostgreSQL version 10, updating to 2.7.5.

Update psycopg to version 2.7.5

---

pgsqltoolsservice/language/completion/packages/sqlcompletion.py
pgsqltoolsservice/language/completion/pgcompleter.py
requirements.txt
tests/language/completion/test_smart_completion_public_schema_only.py

* update allows VS Code debugger to attach to Azure Data Studio extensions
* also fixes enable_attach error

Update PTVSD from 2.20 to 4.3.2

---

pgsqltoolsservice/driver/types/driver.py
pgsqltoolsservice/driver/types/psycopg_driver.py
pgsqltoolsservice/driver/types/pymysql_driver.py
pgsqltoolsservice/query/batch.py
pgsqltoolsservice/query_execution/query_execution_service.py

* added new abstract driver property query_canceled_error to access psycopg2.extensions.QueryCanceledError
* altered query exception handling to use abstracted driver properties
* fixed batch execute function to avoid "cursor does not exist" operational error

Fix query exception handling

---

pgsqltoolsservice/language/metadata_executor.py
pgsqltoolsservice/language/operations_queue.py

* fixed metadata executor to call ServerConnection function get_cursor()
* passed logger into CompletionRefresher

Fixed pg table completion

---

ossdbtoolsservice/driver/types/psycopg_driver.py
ossdbtoolsservice/driver/types/pymysql_driver.py
tests/admin/test_admin_service.py
tests/connection/test_connection_service.py
tests/edit_data/test_smo_edit_table_metadata_factory.py
tests/language/completion/test_mysql_naive_completion.py
tests/language/completion/test_naive_completion.py
tests/language/test_completion_refresher.py
tests/language/test_metadata_executor.py
tests/metadata/test_metadata_service.py
tests/mysqlsmo_tests/utils.py
tests/object_explorer/test_object_explorer_service.py
tests/pgsmo_tests/node_test_base.py
tests/pgsmo_tests/test_node_objects.py
tests/pgsmo_tests/test_object_database.py
tests/pgsmo_tests/test_object_server.py
tests/pgsmo_tests/utils.py
tests/query/test_batch.py
tests/query/test_query.py
tests/query_execution/test_query_execution_service.py
tests/scripting/test_scripter.py
tests/scripting/test_scripting_service.py
tests/utils.py

I added a MySQL completer and edited completion refresher to handle multiple providers, so I am adding tests to test that functionality now.

New mysql completer and completion refresher tests

---

pgsmo/objects/functions/macros/variable.macros
pgsmo/objects/functions/templates_functions/pg/+default/create.sql
pgsmo/objects/functions/templates_functions/pg/11.0_plus/create.sql
pgsmo/objects/functions/templates_functions/pg/12.0_plus/create.sql
pgsmo/objects/functions/templates_functions/pg/12.0_plus/get_support_functions.sql
pgsmo/objects/functions/templates_functions/pg/12.0_plus/properties.sql
pgsmo/objects/functions/templates_functions/pg/12.0_plus/update.sql
pgsmo/objects/functions/templates_functions/pg/9.2_plus/create.sql
pgsmo/objects/functions/templates_functions/pg/9.5_plus/create.sql
pgsmo/objects/table/templates/12.0_plus/properties.sql
requirements.txt

Fixing these issues,
Table create as script
- https://github.com/microsoft/azuredatastudio-postgresql/issues/225
Function create as script
- https://github.com/microsoft/azuredatastudio-postgresql/issues/72

Fixing bug for Table 'Script as Create' and Function 'Script as Create'

---

ossdbtoolsservice/language/language_service.py
scripts/test-all.sh
tests/integration/integration_tests.py

RCA: 
Because of Encoded URL of file path, the file was not recognized by the formatter. 
Issue:
https://github.com/microsoft/azuredatastudio-postgresql/issues/251

Fix document formatting issue 

---

ossdbtoolsservice/language/language_service.py
pgsmo/objects/server/server.py

Fixing 
https://github.com/microsoft/azuredatastudio-postgresql/issues/152
RCA: searching function objects not finding parent schema
Solution: Use different logic to find function object from searching database

Fix get definition for function and table

---

ossdbtoolsservice/driver/types/pymysql_driver.py

Fix for: 
https://github.com/microsoft/azuredatastudio-mysql/issues/39

Fixing ssl disable throwing error for MySQL

---

ossdbtoolsservice/driver/types/pymysql_driver.py

Fix for https://github.com/microsoft/azuredatastudio-mysql/issues/25

Fixing get_database_size for no tables scenario

---

ossdbtoolsservice/workspace/contracts/common.py

Ignore extra attributes of text document position to fix broken language service

Fix broken language service

---

.gitignore
ossdbtoolsservice/language/completion/packages/pgliterals/main.py
ossdbtoolsservice/language/completion_refresher.py
ossdbtoolsservice_main.spec
requirements.txt

* Update initialize_request.py
* Change packaging to support all platforms

Changing package to support all platforms (#391)

---

ossdbtoolsservice/capabilities/contracts/initialize_request.py
pgsmo/objects/view/materialized_view_templates/pg/9.3_plus/select.sql

https://github.com/microsoft/azuredatastudio-postgresql/issues/270
Fix syntax for the sql file

Fix materialized view error

---

.pipeline/build-CI.yml
.pipeline/build_pullrequest.yml
.pipeline/build_release.yml
.pipeline/templates/build.yml

Addressing: 
https://github.com/microsoft/pgtoolsservice/issues/371

Create yml file for release build and updates, including unit tests for Windows

---

pgsmo/objects/functions/templates_functions/pg/+default/create.sql
pgsmo/objects/functions/templates_functions/pg/11.0_plus/delete.sql
pgsmo/objects/functions/templates_procedures/pg/+default/delete.sql

Remove quotation marks added to function and procedures name during drop

---

ossdbtoolsservice/driver/types/driver.py
ossdbtoolsservice/driver/types/psycopg_driver.py
ossdbtoolsservice/language/completion/packages/pgliterals/pgliterals.json
ossdbtoolsservice/query/batch.py
ossdbtoolsservice/query/query.py
ossdbtoolsservice/query_execution/query_execution_service.py
tests/query_execution/test_pg_query_execution_service.py
tests/utils.py

Psycopg 3 update, auto commit set to true automatically. Need to check for user defined transaction. 
addressing:  [#433](https://github.com/microsoft/azuredatastudio-postgresql/issues/433)
Edit messaging:

Psycopg3 Transactions update

---

ossdbtoolsservice/converters/pg_converters/any_to_bytes_converters.py

Addressing: https://github.com/microsoft/azuredatastudio-postgresql/issues/446

Fix Object of type UUID is not JSON serializable

---

ossdbtoolsservice/driver/types/psycopg_driver.py
tests/utils.py

use psycopg function for connection parameters parsing

use psycopg function for parsing

---

ossdbtoolsservice/query/batch.py
ossdbtoolsservice/query_execution/query_execution_service.py
tests/query_execution/test_pg_query_execution_service.py
tests/utils.py

For: https://github.com/microsoft/azuredatastudio-postgresql/issues/455

Update RAISE command and Messages

---

ossdbtoolsservice/converters/pg_converters/any_to_bytes_converters.py

For:
https://github.com/microsoft/azuredatastudio-postgresql/issues/449
https://github.com/microsoft/azuredatastudio-postgresql/issues/426

Address not being able to convert byte and inet

---

pgsmo/objects/functions/function_base.py
pgsmo/objects/table_objects/trigger.py
tests/pgsmo_tests/test_object_trigger.py

add cascade to drop for trigger and properly format drop script for functions/procedures/trigger functions

Fix drop scripts for triggers and functions/procedures/trigger functions

---

ossdbtoolsservice/driver/types/psycopg_driver.py

https://github.com/microsoft/pgtoolsservice/issues/431
https://github.com/microsoft/azuredatastudio-postgresql/issues/472
Before:
After:

Provide better error messages

---

DEVELOPING.md
Dockerfile
README.md
docker-compose.web.yml
setup.cfg
webserver_client/Dockerfile
webserver_client/package.json

Fix the docker build for the web server, which was broken. Add a docker-compose method of spinning it and the test client locally. Updated docs.

Update webserver docker and docs

---

ossdbtoolsservice/chat/completion/vscode_chat_completion.py
ossdbtoolsservice/chat/plugin/docs_plugin.py
ossdbtoolsservice/chat/plugin/postgres_plugin.py

Fixes a notification with the incorrect method on execute_sql_query_readonly in the error case.
Sends missing notification for docs plugin in error case.

Fix issues with function calling notifications
