- pgsqltoolsservice/language/language_service.py
We are directly using the text document uri which is encoded, hence now using the decoded url which is by using file_url from script file.
Similar fix to mssql extension: https://github.com/microsoft/sqltoolsservice/pull/910
> Fix for skipping intellisense for non pgsql language flavor

- pgsqltoolsservice/capabilities/capabilities_service.py
- pgsqltoolsservice/capabilities/contracts/capabilities_request.py
- pgsqltoolsservice/connection/connection_service.py
- tests/connection/test_connection_service.py
ADS sends azureAccountToken (instead of password) for Azure Active Directory login. PostgreSQL for Azure wire protocol takes the access token in place of a password for AAD users. 
So, a) accept azureAccountToken as a connection parameter, and b) send it as a password to PostgreSQL.
> Add ability for service to accept azureAccountToken from ADS client

- pgsqltoolsservice/query/query.py
- tests/query/test_query.py
This is a fix for microsoft/azuredatastudio-postgresql#160 which is caused by using ```sqlparse``` package which treats the '#' character as a comment delimiter. This is correct behavior in My SQL while PostgreSQL uses it for XOR operator. As a result, the queries like
```
select 
42 # 24 AS "Xor",
~1 AS "Negation";
```
cause syntax error because they get converted to
```
select 42 ~ 1 AS "Negation";
```
or even worse, the ```select 42 # 24;``` is executed as ```select 42``` and it succeeds but it returns incorrect result (42 instead of 50).
With the proposed changes, we will only use the formatted SQL for detecting empty statements and pass the original unformatted SQL for execution.
This is not the best fix available because the same ```sqlparse``` package is still used for splitting …
> Use original unformatted query text for execution

- pgsqltoolsservice/converters/bytes_to_any_converters.py
- tests/query/data_storage/test_service_buffer_file_stream_reader.py
This is a fix for: 
https://github.com/microsoft/azuredatastudio-postgresql/issues/130
https://github.com/microsoft/azuredatastudio-postgresql/issues/192
When json data is returned by PostgreSQL, the service runs it through a converter that produces the output that looks like json but it is invalid because it uses Python syntax (e.g. single quotes, capitalized boolean values, etc.)
There is no point to convert the server output because it is already json, and it is already treated as json by the service when it loads it into the python dictionary.
> Do not convert JSON returned by the server

- pgsmo/utils/templating.py
We are hitting issues in macos in expanding database object nodes as we are looking for '\\' in path which does not exist and uses the wrong query to get the objects.
> Use ps.path.basename to get the folder name

- pgsqltoolsservice/query/batch.py
- pgsqltoolsservice/query/query.py
When connection is closed by server, the qurery execution fails but we were trying to set autocommit to true on a closed connection which throws an error.
Now check the status of the connection. This will ensure that the status is set to executed and user can connect/disconnect properly.
> Fix query editor connect/disconnect

- pgsmo/objects/view/view_templates/pg/9.1_plus/properties.sql
There is a syntax error in create view query, Remove extra ',' .
> Fix create as view query syntax error

- ossdbtoolsservice/capabilities/connection_options/mysql_connection_options.py
- ossdbtoolsservice/driver/types/pymysql_driver.py
Adding AAD authorization for MySQL databases (without the previously added package.json file). Fixed:
- Adding azureaccounttoken as a connection property
- Setting the token as the password if a token is provided. This way if AAD auth is used, AAD token replaces standard password when authenticating
> Adding AAD authorization for MySQL databases -- Updated

- tests/connection/test_mysql_connection_service.py
- tests/connection/test_pg_connection_service.py
* Added a new file for MySQL connection service tests and tested connect and connect with azure account token (newly added in #261)
> Add new MySQL connection service tests

- tests/json_rpc_tests/object_explorer_json_rpc_tests.py
* Edit expected_session_id in object_explorer_json_rpc_tests to include port (added with MySQL changes).
* Edit expected_session_id to urllib.quote() user, host, and dbname to match what object_explorer_service does. This test used to fail if the database it was connecting to had a special symbol like "@" in the username because the expected_session_id would not match the actual session_id in object_explorer_service.
> Fix object_explorer_json_rpc_tests

- requirements.txt
* Add pydevd dependency to requirements.txt because vsix package was throwing module missing errors.
> Add pydevd dependency

- ossdbtoolsservice/language/language_service.py
- ossdbtoolsservice/workspace/__init__.py
- ossdbtoolsservice/workspace/contracts/__init__.py
- tests/language/test_language_service.py
* Fixed language service to grab provider specific format doc configurations, instead of always taking the PG configs. This fixed MySQL format document request handling. 
* Added MySQL format doc tests and doc range tests
> Fix MySQL format document request handling

- requirements.txt
- setup.py
pydev_runfiles module is not being added to the package created by cx_freeze, adding it explicitly to be included
> Explicitly include pydev_runfiles to fix module not find error

- ossdbtoolsservice/query/data_storage/service_buffer_file_stream_reader.py
- ossdbtoolsservice/query/data_storage/service_buffer_file_stream_writer.py
Issues:
microsoft/azuredatastudio-postgresql#168
microsoft/azuredatastudio-postgresql#143
microsoft/azuredatastudio-postgresql#236
RCA:
empty string and null value are both written in bytes array '0000 0000'
Added one more logic to differentiate NULL value and non Null value
> Fix empty string shown as null value

- ossdbtoolsservice/capabilities/connection_options/pg_connection_options.py
Add 'isIdentity= true' to the port and host option in package.json, this will make ADS be able to treat them as different connections.
Tied with ADS fix: microsoft/azuredatastudio#17229
Tied with pg extension fix: https://github.com/microsoft/azuredatastudio-postgresql/pull/293
This PR fixes microsoft/azuredatastudio-postgresql#113
> Have ADS treat connections as different through port and host

- ossdbtoolsservice/connection/connection_service.py
The Connection error dialog shown to users without set firewall rules suggest checking the firewall settings.
Check that the server address or hostname is the full address to the Connection Error message dialog.
This PR fixes #
microsoft/azuredatastudio-postgresql#133
microsoft/azuredatastudio-postgresql#132
> Add suggestions to error

- ossdbtoolsservice/language/completion/mysql_completer.py
- ossdbtoolsservice/language/completion_refresher.py
Functions refresh was failing because it was happening before schemata refresh in ordered dictionary. As a result, all the subsequent refreshes in the dictionary were failing. Changed the order in dictionary to fix the issue.
> fixing autocomplete refresh for functions and views

- ossdbtoolsservice/metadata/metadata_service.py
- tests/metadata/test_metadata_service.py
Issue Summary:
In Dashboard, create as script not working on stored procedure.
RCA:
Because of object_type_name being empty,[ sql-opsdataprotocol client is setting object_type_name](https://github.com/microsoft/sqlops-dataprotocolclient/blob/205a11059edf0dabfe052897050705ac10da4c94/src/protocolConverter.ts#L27) to StoredProcedure.
And Mysql toolsservice expects object_type_name as 'Procedure' in script-as-create request for Stored Procedures.
Fix:
Stated passing object_type_name in object metadata
> Dashboard procedure script fix

- pgsmo/objects/table/templates/+default/acl.sql
- pgsmo/objects/table/templates/+default/get_oid.sql
- pgsmo/objects/table/templates/+default/get_relations.sql
- pgsmo/objects/table/templates/+default/get_table.sql
- pgsmo/objects/table/templates/+default/nodes.sql
- pgsmo/objects/table/templates/+default/properties.sql
- pgsmo/objects/table/templates/9.1_plus/acl.sql
- pgsmo/objects/table/templates/9.1_plus/nodes.sql
- pgsmo/objects/table/templates/9.1_plus/properties.sql
- pgsmo/objects/table_objects/column/+default/nodes.sql
- pgsmo/objects/table_objects/column/9.2_plus/nodes.sql
Fixes https://github.com/microsoft/azuredatastudio-postgresql/issues/126
Fixes https://github.com/microsoft/azuredatastudio-postgresql/issues/156
> Fix display of partitioned tables

- ossdbtoolsservice/query/data_storage/save_as_csv_writer.py
- ossdbtoolsservice/query/data_storage/save_as_excel_writer.py
- ossdbtoolsservice/query/file_storage_result_set.py
- ossdbtoolsservice/query_execution/contracts/save_result_as_request.py
- tests/query/data_storage/test_save_as_csv_writer.py
- tests/query/data_storage/test_save_as_excel_writer.py
Give raw object when saving as excel. Keeps integers as numeric. [318](https://github.com/microsoft/azuredatastudio-postgresql/issues/318)
Fix delimiter [262](https://github.com/microsoft/azuredatastudio-postgresql/issues/262) :
Fix new lines add in CSV [238](https://github.com/microsoft/azuredatastudio-postgresql/issues/238)
Show error during save fail:
> Addressing Save As issues from queries

- ossdbtoolsservice/object_explorer/routing/pg_routing.py
This fix enables table objects to be expanded again. We take the schema value from the table object's parent node instead of the node itself.
> Hotfix for allowing table objects to be expanded again

- ossdbtoolsservice/driver/types/adapter.py
- ossdbtoolsservice/driver/types/psycopg_driver.py
- ossdbtoolsservice/query/batch.py
- tests/connection/test_adapters.py
- tests/language/test_language_service.py
- tests/query_execution/test_pg_query_execution_service.py
- tests/utils.py
Fix for https://github.com/microsoft/azuredatastudio-postgresql/issues/457
Add customized adapters to handle timestamp edge cases that are outside of Python's date datatype's min and max values
Dates smaller than Min or bigger than max values will be represented in Python's date datatype's min and max values
table
ADS
> Fix edge cases handling for date datetime timestamp

- .pipeline/build_pullrequest.yml
Making this change in the PR build because:
- PR builds are not meant for distribution or use, only to confirm that it compiles and passes tests
- As it's a non-production build, it doesn't have signing.
This is similar to the approach followed by the sister project [sqltoolsservice](https://github.com/microsoft/sqltoolsservice/blob/main/azure-pipelines/build-and-release.yml).
> Rm code signing from pullrequest build

- CODEOWNERS
This team is taking ownership of the PGTS project for use in several upcoming developer tool projects. This change leaves the existing group (`azurepostgresql`) with the same ownership status, simply adds an additional team.
Here's a link to the [CODEOWNERS syntax](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners#codeowners-syntax) to verify that it is space-delimited.
> Update CODEOWNERS to indclude PG DevX team

- pgsmo/objects/view/materialized_view_templates/pg/9.3_plus/properties.sql
- pgsmo/objects/view/materialized_view_templates/pg/9.4_plus/properties.sql
- pgsmo/objects/view/materialized_view_templates/ppas/9.3_plus/properties.sql
The value `did` was not passed into the template context, and it was expecting the value `oid` which is provided. Updating the template prevents a syntax error from the empty render caste to ::oid and now MV Create scripting works.
> Use correct arg name for Materialized View scripting templates

- ossdbtoolsservice/capabilities/connection_options/pg_connection_options.py
This option is used for clients to generate and validate UIs for different methods to authenticate with.
Implementation similar to STS https://github.com/microsoft/sqltoolsservice/blob/9cb8082c62dea05102e47b18efd958f11e8dabc2/src/Microsoft.SqlTools.ServiceLayer/Connection/ConnectionProviderOptionsHelper.cs#L66C13-L82C23
> Add connection option for AuthenticationType

- .github/workflows/dev-build.yml
- scripts/build.ps1
- scripts/build.sh
- scripts/get-artifact-name.sh
This modifies the dev artifact publishing to use pre-release Releases instead of gh-pages.
The binaries created in #501 are too large to handle as repo files. GitHub Releases with the pre-release option seem like a good fit for this purpose. 
This will create releases when tags like `v1.10.1-dev.1` are created. It provides an auto-generated changelog. 
Releases will look like this (except a tag like `v1.10.1-dev.1` as the title instead of `refs/heads/...`:
> Add development releases

- ossdbtoolsservice/edit_data/edit_data_service.py
- ossdbtoolsservice/main.py
- ossdbtoolsservice/query_execution/contracts/result_set_notification.py
- ossdbtoolsservice/query_execution/query_execution_service.py
- ossdbtoolsservice/scripting/contracts/script_as_request.py
- ossdbtoolsservice/scripting/scripting_service.py
- ossdbtoolsservice/serialization/serializable.py
- tests/query/test_query.py
- tests/query_execution/test_pg_query_execution_service.py
- tests/scripting/test_scripting_service.py
Fixes two issues introduced by recent refactoring:
Batch queries that raised an exception while executing were masking the initial db exception and throwing a custom error, which was displayed to the user. This has been resolved to allow the original db error to be displayed by updating the expected types for resultSetSummaries.
Scripting requests were not having their parameters correctly deserialized and as a result, object property accessors were being called on a `dict`. The `ObjectMetadata` attribute type for `scripting_object` originally had a hacky deserialization workaround because the client/server contracts were misaligned for making a script request. When that was removed for typing fixes, the
parameter was no longer getting deserialized into the correct type, and was left a …
> Correct query exception details and fixes for "Script As" requests

- ossdbtoolsservice/object_explorer/contracts/get_session_id_request.py
- ossdbtoolsservice/object_explorer/object_explorer_service.py
- tests_v2/object_explorer/test_object_explorer_service.py
Adds a method to retrieve an owner_uri/session_id of a connection, given a `ConnectionDetails` object. This matches functionality in SQL Tools Service, and will be used in a VS Code extension update in the future.
Port of https://github.com/microsoft/sqltoolsservice/pull/2443
> Method to retrieve session id (owner uri) of connection

- ossdbtoolsservice/chat/plugin/postgres_plugin.py
The PostgresPlugin sends back status to the vscode chat participant, and includes emojis in those status messages. I also started logging those, however the logging sometimes chokes on the unicode characters of the emojis. This removes the emojis from the log messages.
> Remove emojis from logging.

- ossdbtoolsservice/object_explorer/contracts/close_session_request.py
- ossdbtoolsservice/object_explorer/contracts/get_session_id_request.py
- ossdbtoolsservice/object_explorer/object_explorer_service.py
- tests/object_explorer/test_object_explorer_service.py
SqlToolsService has a [more complex response type](https://github.com/microsoft/sqltoolsservice/blob/09696ddd9e368685ab48edd87dea90b0a35df23d/src/Microsoft.SqlTools.ServiceLayer/ObjectExplorer/Contracts/CloseSessionRequest.cs#L17) for requests to close a session. Update PGTS to match so that client code can be unified between them. Also updates the serialization alias for GetSessionId to allow for client access using camel case.
> Update session close response to match STS

- ossdbtoolsservice/connection/connection_service.py
- ossdbtoolsservice/connection/contracts/common.py
- ossdbtoolsservice/object_explorer/object_explorer_service.py
- ossdbtoolsservice/utils/connection.py
A recent change to the client behavior meant that the object explorer would send a standardized `ownerUri` based on connection details. Previously, the inconsistency meant that the map of connections tracked by the tools service connection manager actually had two different connections stored for the same object explorer session.
Now that a single URI was used, the tools service should have been able to just use the single connection. However, the existing implementation caused a bug and consistent race condition. When the connection manager got the request the for second connection request, it would now correctly see that it already had a connection for these details (via the URI). It then checked to see if the connection details had changed. In the cases where client-optional values …
> Object Explorer session connection mapping accounts for default connection values

- ossdbtoolsservice/driver/types/driver.py
- ossdbtoolsservice/query/query.py
- tests/connection/test_driver.py
- tests/query_execution/test_pg_query_execution_service.py
The "show actual plan" option has been set to the incorrect syntax
`ANALYZE EXPLAIN` since it was committed about 8 years ago. This has
been swapped with the correct syntax `EXPLAIN ANALYZE` and a test has
been added to confirm.
There was a bug in translating connection properties from some internal
names to the ones psycopg expect. This prevented properties like
`connect_timeout` from being applied to the connection. This has been fixed a
a test added to check the properties have been transformed as expected.
> Fixs bugs in EXPLAIN ANALYZE and ServerConnection parameters

- ossdbtoolsservice/chat/completion/messages.py
- ossdbtoolsservice/chat/completion/vscode_chat_completion.py
- ossdbtoolsservice/chat/messages.py
- ossdbtoolsservice/chat/plugin/postgres_plugin.py
- ossdbtoolsservice/core/models.py
- ossdbtoolsservice/object_explorer/contracts/close_session_request.py
- ossdbtoolsservice/object_explorer/contracts/create_session_request.py
- ossdbtoolsservice/object_explorer/contracts/get_session_id_request.py
- ossdbtoolsservice/object_explorer/object_explorer_service.py
Sets model configuration shared by models serialized and deserialized in the server by creating a blanket alias generator that converts to/from camel, and allows 'populate_by_name', which enables the non-alias name to be used in model initialization code.
> Use base pydantic model for config.

- ossdbtoolsservice/query/data_storage/save_as_writer.py
- ossdbtoolsservice/scripting/scripting_service.py
- tests/query/data_storage/test_save_as_csv_writer.py
- tests/query/data_storage/test_save_as_excel_writer.py
- tests/query/data_storage/test_save_as_json_writer.py
Results Exports that included column subsets (selections from the results viewer) incorrectly calculated the "end" column. This resulted in these exports having the correct number of rows, but no data, as the column range produced an empty iteration.
Also add indentation formatting to "scripts" from the ScriptingService, which were previously without indentation.
Fixes https://github.com/azure-data-database-platform/vs-code-postgresql/issues/157
Fixes https://github.com/azure-data-database-platform/vs-code-postgresql/issues/175
> Export selections of results

- ossdbtoolsservice/capabilities/connection_options/pg_connection_options.py
- ossdbtoolsservice/hosting/json_writer.py
The json message content of the LSP contain values directly from a user database. These messages shouldn't be logged or persisted anywhere, so the entire content of the message has been removed.
Also updates the default value for client_encoding to instruct clients to prefer utf8 if not user value is specified.
Fixes #527
> Remove message content from logs

- ossdbtoolsservice/chat/completion/vscode_chat_completion.py
- ossdbtoolsservice/scripting/scripting_service.py
- pgsmo/objects/table/templates/+default/select.sql
- pgsmo/objects/view/materialized_view_templates/pg/9.3_plus/select.sql
- pgsmo/objects/view/view_templates/pg/9.1_plus/select.sql
The scripting service recently was changed to include sqlparse formatting prior to returning the generated sql. However, this formatting doesn't produce well formatted results in many cases. Instead, the formatter calls were removed, and the sql templates that were producing the original poorly formatted results were changed to be formatted nicely, as all other scripting templates are.
The formatting is still an issue in generally, and that is being tracked here https://github.com/microsoft/pgtoolsservice/issues/533
> Remove formatting for scripting service

- ossdbtoolsservice/chat/chat_history_manager.py
- ossdbtoolsservice/chat/chat_service.py
- ossdbtoolsservice/connection/core/connection_manager.py
This PR fixes two issues:
Previously, the user message hash was used to identify a spot in a conversation history that the tool call history should be inserted. This presented an issue whe messages from the user were the same - particularly, "yes" is a common message because the model often asks "would you like me to proceed?". This would cause an error when the chat history manager attempted to insert a tool call history multiple times.
Instead, we use the index of the user message in the chat history as the identifier. This should remain consistent across CompletionRequest calls as the history is append-only for a single session.
Errors were popping up around psycopg-generated prepared statements not existing. This is likely due to the sharing of connections via the connection pool in …
> Chat fixes

- ossdbtoolsservice/connection/contracts/common.py
- ossdbtoolsservice/connection/core/connection_class.py
- ossdbtoolsservice/connection/core/connection_manager.py
- tests/workspace/test_workspace_service.py
- tests_v2/connection/conftest.py
- tests_v2/connection/core/test_connection_details.py
- tests_v2/connection/core/test_connection_manager.py
There was some bad logic in the azure token refresh for the connection manager; this PR fixes that.
First issue was that the new azure token was being set into the ConnectionDetails object, with the intention that the new token would be used in future connection params in the pool. However, the setting of the azure token to the password field happened once on ConnectionPool initialization during details.get_connection_params(), which gave ConnectionPool a static dictionary of values for connection parameters. Updating the connection detail token had no effect on the password connection parameter in this case.
Additionally, the refresh logic was incorrectly setting the entire AzureToken class to the kwargs['password'] field for the initial refresh connection parameters, which were being …
> Fixes issue with azure token refresh
